# Generated by Django 5.2.6 on 2025-12-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
