# Generated by Django 5.2.6 on 2025-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_sort_order_alter_projectscreenshot_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Drag & drop rows in the admin list to reorder projects.', verbose_name='Order'),
        ),
    ]
