from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS api_analyticsevent (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        event_type varchar(50) NOT NULL,
                        path varchar(300) NOT NULL,
                        referrer varchar(500) NOT NULL,
                        language varchar(50) NOT NULL,
                        country varchar(2) NOT NULL DEFAULT '',
                        os varchar(50) NOT NULL DEFAULT '',
                        screen_width integer NULL CHECK (screen_width >= 0),
                        screen_height integer NULL CHECK (screen_height >= 0),
                        anonymous_id varchar(64) NOT NULL,
                        created_at timestamp with time zone NOT NULL
                    );

                    ALTER TABLE api_analyticsevent
                    ADD COLUMN IF NOT EXISTS country varchar(2) NOT NULL DEFAULT '';

                    ALTER TABLE api_analyticsevent
                    ADD COLUMN IF NOT EXISTS os varchar(50) NOT NULL DEFAULT '';

                    CREATE INDEX IF NOT EXISTS api_analyticsevent_event_type_idx
                    ON api_analyticsevent (event_type);

                    CREATE INDEX IF NOT EXISTS api_analyticsevent_country_idx
                    ON api_analyticsevent (country);

                    CREATE INDEX IF NOT EXISTS api_analyticsevent_anonymous_id_idx
                    ON api_analyticsevent (anonymous_id);

                    CREATE INDEX IF NOT EXISTS api_analyticsevent_created_at_idx
                    ON api_analyticsevent (created_at);
                    """,
                    reverse_sql="""
                    DROP TABLE IF EXISTS api_analyticsevent;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AnalyticsEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "event_type",
                            models.CharField(
                                choices=[
                                    ("page_view", "Page view"),
                                    ("contact_submit", "Contact form submit"),
                                ],
                                db_index=True,
                                default="page_view",
                                max_length=50,
                            ),
                        ),
                        ("path", models.CharField(max_length=300)),
                        ("referrer", models.CharField(blank=True, max_length=500)),
                        ("language", models.CharField(blank=True, max_length=50)),
                        (
                            "country",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=2,
                            ),
                        ),
                        ("os", models.CharField(blank=True, max_length=50)),
                        (
                            "screen_width",
                            models.PositiveIntegerField(blank=True, null=True),
                        ),
                        (
                            "screen_height",
                            models.PositiveIntegerField(blank=True, null=True),
                        ),
                        (
                            "anonymous_id",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                help_text=(
                                    "Client-side anonymous id created only after "
                                    "analytics consent."
                                ),
                                max_length=64,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ("-created_at",),
                    },
                ),
            ],
        ),
    ]