# Generated by Codex on 2026-07-02

from django.db import migrations, models


def populate_screenshot_order(apps, schema_editor):
    Project = apps.get_model("api", "Project")
    ProjectScreenshot = apps.get_model("api", "ProjectScreenshot")

    for project in Project.objects.order_by("sort_order", "id"):
        screenshots = ProjectScreenshot.objects.filter(project=project).order_by("id")

        for order, screenshot in enumerate(screenshots, 1):
            screenshot.sort_order = order
            screenshot.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_enrich_analytics_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectscreenshot",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Drag & drop rows in the admin to choose screenshot order.",
                verbose_name="Order",
            ),
        ),
        migrations.RunPython(
            populate_screenshot_order,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="projectscreenshot",
            options={"ordering": ("project", "sort_order", "id")},
        ),
    ]
