# Generated by Codex on 2026-07-02

from django.db import migrations


def resequence_screenshot_order(apps, schema_editor):
    ProjectScreenshot = apps.get_model("api", "ProjectScreenshot")

    screenshots = ProjectScreenshot.objects.select_related("project").order_by(
        "project__sort_order",
        "project__id",
        "sort_order",
        "id",
    )

    for order, screenshot in enumerate(screenshots, 1):
        screenshot.sort_order = order
        screenshot.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_projectscreenshot_sort_order"),
    ]

    operations = [
        migrations.RunPython(
            resequence_screenshot_order,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="projectscreenshot",
            options={"ordering": ("sort_order", "id")},
        ),
    ]
