# Generated by Django 5.2.6 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_reorder_screenshots_globally"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectscreenshot",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Drag & drop rows in the admin list to choose screenshot order.",
                verbose_name="Order",
            ),
        ),
    ]
