# Generated by Django 5.2.6 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_projectscreenshot_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("badge", "Badge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("issued_at", models.DateField()),
                ("credential_id", models.CharField(blank=True, max_length=200)),
                ("credential_url", models.URLField(blank=True)),
                ("image_url", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("python", "Python"),
                            ("database", "Database"),
                            ("docker", "Docker"),
                            ("cloud", "Cloud"),
                            ("linux", "Linux"),
                            ("networking", "Networking"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of short tags, for example ["Python", "Django"].',
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Drag & drop rows in the admin list to reorder credentials.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
