# Generated by Django 5.2.6 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_credential_analytics_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("python", "Python"),
                    ("database", "Database"),
                    ("docker", "Docker"),
                    ("cloud", "Cloud"),
                    ("linux", "Linux"),
                    ("networking", "Networking"),
                    ("security", "Security"),
                    ("it_fundamentals", "IT Fundamentals"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
