# Generated by Django 5.2.6 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_credential_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="client_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone reported by the browser, for example Europe/Berlin.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="utc_offset_minutes",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Browser UTC offset in minutes at the time of the event.",
                null=True,
            ),
        ),
    ]
