databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user

services:
  - type: web
    name: portfolio-backend
    rootDir: backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "poetry run gunicorn portfolio_backend.wsgi --workers 3 --threads 2 --bind 0.0.0.0:$PORT --log-file -"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: DJANGO_ADMIN_URL
        value: deus_ex_adm
      - key: DJANGO_SUPERUSER_USERNAME
        value: maxx
      - key: DJANGO_SUPERUSER_EMAIL
        value: m.petrykin@gmx.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: POETRY_VIRTUALENVS_CREATE
        value: false

  - type: static
    name: portfolio-frontend
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: portfolio-backend
          property: host