databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user

services:
  - type: web
    name: portfolio-backend
    rootDir: backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "poetry run gunicorn portfolio_backend.wsgi --workers 3 --threads 2 --bind 0.0.0.0:$PORT --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

  - type: static
    name: portfolio-frontend
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_TURNSTILE_SITEKEY
        sync: false
      - key: VITE_SNOW
        value: auto